version: "1.0.0"
services:
  local:
    build:
      context: .
      dockerfile: Dockerfile
    image: staffys_api
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - /app/dist
    env_file:
      - ./.env
    container_name: staffys_api_local
    ports:
      - 4000:4000
    tty: true
    entrypoint: ["npm", "run", "dev"]
    networks:
      - staffys_api_network
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: staffys_api
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - /app/dist
      - /app/coverage
    env_file:
      - ./.env.testing
    container_name: staffys_api_local_tests
    ports:
      - 9000:9000
    tty: true
    entrypoint: ["npm", "run", "test:watch"]
    networks:
      - staffys_api_network
networks:
  staffys_api_network:
    name: staffys_api_network
    driver: bridge
