export const users = [
  {
    name: "Rodrigo",
    lastname: "Escalera",
    password: "12345",
    email: "rodri123@mail.com",
    urlphoto: "hola",
  },
  {
    name: "Emanuel",
    lastname: "Amico",
    password: "12345",
    email: "ema123@mail.com",
    urlphoto: "hola",
  },
  {
    name: "Rafael",
    lastname: "Mojica",
    password: "12345",
    email: "rafa123@mail.com",
    urlphoto: "hola",
  },
  {
    name: "Santiago",
    lastname: "Estevez",
    password: "12345",
    email: "santi123@mail.com",
    urlphoto: "hola",
  },
  {
    name: "Admin",
    lastname: "1",
    password: "12345",
    email: "admin1@mail.com",
    urlphoto: "hola",
    isAdmin: true,
  },
  {
    name: "Admin",
    lastname: "2",
    password: "12345",
    email: "admin2@mail.com",
    urlphoto: "hola",
    isAdmin: true,
  },
  {
    name: "admin",
    lastname: "3",
    password: "12345",
    email: "admin3@mail.com",
    urlphoto: "hola",
    isAdmin: true,
  },
];

export const packages = [
  {
    adress: "calle falsa 10",
    receptorName: "Rodrigo",
    weight: 5,
    deadlines: new Date("2023-07"),
    city: "salta",
  },
  {
    adress: "calle falsa 13",
    receptorName: "Ema",
    weight: 5,
    deadlines: new Date("2023-07"),
    city: "Buenos Aires",
  },
  {
    adress: "calle falsa 12",
    receptorName: "Santi",
    weight: 5,
    deadlines: new Date("2023-07"),
    city: "Buenos Aires",
  },
  {
    adress: "calle falsa 3",
    receptorName: "Rafa",
    weight: 5,
    deadlines: new Date("2023-07"),
    city: "Bogota",
  },
];
